### PR TITLE
Add the `jmul` and `jmult` convenience functions

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by chriselrod** [comment]
Could you replace `size(A, 1)` and `size(B, 2)` with `size(A, StaticInt{1}())` and `size(B, StaticInt{2}())`, respectively? These would be safely type stable with statically sized arrays.
Although I also want to add a `similar` method that creates statically sized arrays when possible. I don't think I really have that yet.

Or maybe we should just create a `StrideArray{promote_type(eltype(A),eltype(B))}(undef, (M,N))`.

**Comment by DilumAluthge** [comment]
> Could you replace `size(A, 1)` and `size(B, 2)` with `size(A, StaticInt{1}())` and `size(B, StaticInt{2}())`, respectively?

Done.

**Comment by DilumAluthge** [comment]
> Or maybe we should just create a `StrideArray{promote_type(eltype(A),eltype(B))}(undef, (M,N))`.

And done.

**Comment by chriselrod** [comment]
Great, thanks!

**Pull request merged**
